export const FieldClasses = [
    "peer",
    "w-full",
    "flex-1",
    "border",
    "border-slate-300",
    "dark:border-slate-600",
    "rounded-md",
    "px-2",
    "py-1",
    "bg-white",
    "dark:bg-slate-950",
    "text-slate-500",
    "dark:text-slate-300",
    "focus:outline-none",
    "focus:border-sky-500",
    "data-has-addon:rounded-r-none",
    "disabled:border-slate-200",
    "disabled:bg-slate-100",
    "dark:disabled:border-slate-800",
    "dark:disabled:bg-slate-900",
    "data-invalid:border-red-500",
    "invalid:!border-red-500",
];

export const FieldSelectClasses = [

];

export const FieldRangeClasses = [
    "self-center",
    "w-full",
    "h-2",
    "appearance-none",
    "rounded-full",
    "bg-white",
    "dark:bg-slate-950",
    "border",
    "border-slate-300",
    "dark:border-slate-600",
    "[&::-webkit-slider-thumb]:appearance-none",
    "[&::-webkit-slider-thumb]:h-4",
    "[&::-webkit-slider-thumb]:w-4",
    "[&::-webkit-slider-thumb]:rounded-full",
    "[&::-webkit-slider-thumb]:bg-sky-500",
    "[&::-webkit-slider-thumb]:shadow-none",

    "[&::-moz-range-thumb]:h-4",
    "[&::-moz-range-thumb]:w-4",
    "[&::-moz-range-thumb]:rounded-full",
    "[&::-moz-range-thumb]:bg-sky-500",
    "[&::-moz-range-thumb]:border-none",
    "[&::-moz-range-thumb]:shadow-none",

    "disabled:bg-slate-100",
    "disabled:border-slate-200",
    "disabled:[&::-webkit-slider-thumb]:bg-slate-300",
    "disabled:[&::-moz-range-thumb]:bg-slate-300",
    "dark:disabled:bg-slate-900",
    "dark:disabled:border-slate-800",
    "dark:disabled:[&::-webkit-slider-thumb]:bg-slate-700",
    "dark:disabled:[&::-moz-range-thumb]:bg-slate-700",
];

export const FieldAddonClasses = [
    "flex",
    "items-center",
    "border",
    "border-l-0",
    "border-slate-300",
    "dark:border-slate-600",
    "bg-slate-300",
    "dark:bg-slate-600",
    "text-sm",
    "font-medium",
    "text-slate-500",
    "dark:text-slate-800",
    "px-2",
    "rounded-r-md",
    "peer-focus:border-sky-500",
    "peer-disabled:border-slate-200",
    "peer-disabled:bg-slate-200",
    "peer-disabled:text-slate-300",
    "dark:peer-disabled:border-slate-800",
    "dark:peer-disabled:bg-slate-900",
    "dark:peer-disabled:text-slate-700",
    "peer-data-invalid:border-red-500",
    "peer-invalid:!border-red-500",
];